<a href="https://colab.research.google.com/github/Visionaryofthefuture/Machine-Learning/blob/main/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

file ="/content/50_Startups.csv"

In [5]:
df = pd.read_csv(file)
df = pd.DataFrame(df)


In [6]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [18]:
print(df.info())
print(df.describe())
X = df.iloc[:, : -1].values
Y = df.iloc[: , -1].values
type(X)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB
None
           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000

numpy.ndarray

No null values or missing data, needs no cleaning

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct1 = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [3])], remainder = "passthrough")
X = np.array(ct1.fit_transform(X))

In [24]:
''' to see new data'''
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

Encoding state data


In [29]:
# prompt: plot the scatter plot for xabove
'''
plt.scatter(X[:, 1:])
plt.show()'''

X[:, 1:]

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7

In [40]:
X_train ,X_test,Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)

In [41]:
Y_train

array([ 96479.51, 134307.35, 111313.02, 129917.04, 118474.03, 107404.34,
       156991.12,  81229.06, 141585.52,  97483.56,  78239.91, 152211.77,
        71498.49, 105733.54,  96712.8 , 156122.51, 182901.99,  89949.14,
        69758.98, 146121.95,  96778.92, 125370.37, 191050.39, 110352.25,
       105008.31, 108733.99, 101004.64,  65200.33, 155752.6 , 192261.83,
       132602.65,  90708.19,  14681.4 , 122776.86,  97427.84, 191792.06,
       108552.04,  64926.08,  35673.41,  49490.75])

In [42]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [48]:
regressor.fit(X_train, Y_train)

LinearRegression()

In [59]:
k = regressor.predict(X_test)


In [58]:
k = k.reshape(-1, 1)
Y_test = Y_test.reshape(-1, 1)

combined_results = np.concatenate((k, Y_test), axis=1)

print(combined_results)

[[ 45806.01494905  42559.73      ]
 [102339.9440747  103282.38      ]
 [116186.25997665 126992.93      ]
 [135141.60094734 144259.4       ]
 [100460.28080244  99937.59      ]
 [173138.02552718 166187.94      ]
 [ 75585.25835222  77798.83      ]
 [129766.62759231 124266.9       ]
 [ 83126.96446128  81005.76      ]
 [154394.34763975 149759.96      ]]


In [52]:
print(regressor.coef_)
print(regressor.intercept_)

[-6.52208418e+02  7.80906921e+02 -1.28698503e+02  8.11665219e-01
 -3.12027409e-02  2.50739610e-02]
50683.914461409564
